- name: Run the app docker image
  become: true
  docker_container:
    name: "{{ gitlab_image_name }}"
    image: "{{ gitlab_image_url }}"
    state: started
    restart_policy: always
    restart: true
    pull: true
    cleanup: true
    ports:
      - "80:8080"
    env:
      NODE_ENV: "production"
      PORT: "8080"
