variables:
  IMAGE_NODE: node:18.18-alpine
  WEB_DIR: "web"
  SCRIPTS_DIR: "scripts"

default:
  image: alpine:3.17
  tags:
    - kiv

stages:
  - test
  - publish

test-unit-web:
  stage: test
  image: $IMAGE_NODE
  script:
    - cd $WEB_DIR
    - npm install
    - npm run test

# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1986
publish-web-docker-image:
  stage: publish
  script:
    - ./$SCRIPTS_DIR/temp-build-since-kiv-is-bad.sh web
  tags:
    - personal-dont-use-pls
  when: manual

publish-ai-docker-image:
  stage: publish
  script:
    - ./$SCRIPTS_DIR/temp-build-since-kiv-is-bad.sh ai
  tags:
    - personal-dont-use-pls
  when: manual
