variables:
  IMAGE_NODE: node:18.18-alpine
  IMAGE_DOCKER: docker:20.10
  DOCKER_IN_DOCKER_SERVICE: docker:20.10-dind
  WEB_DIR: "web"
  SCRIPTS_DIR: "scripts"

default:
  image: alpine:3.17
  tags:
    - personal-dont-use-pls

stages:
  - test
  - publish

test-unit-web:
  stage: test
  image: $IMAGE_NODE
  script:
    - cd $WEB_DIR
    - npm install
    - npm run test

# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1986
publish-web-docker-image:
  stage: publish
  image: $IMAGE_DOCKER
  services:
    - name: $DOCKER_IN_DOCKER_SERVICE
      alias: docker
  script:
    - ./$SCRIPTS_DIR/temp-build-since-kiv-is-bad.sh web
  when: manual

publish-ai-docker-image:
  stage: publish
  image: $IMAGE_DOCKER
  services:
    - name: $DOCKER_IN_DOCKER_SERVICE
      alias: docker
  script:
    - ./$SCRIPTS_DIR/temp-build-since-kiv-is-bad.sh ai
  when: manual
