services:
  web_service:
    image: "registry.gitlab.com/jamesari/aswi-testing/web-dist:latest"
    networks:
      - api_network
    ports:
      - "8080:8080"

  ai_service:
    image: "registry.gitlab.com/jamesari/aswi-testing/ai-dist:latest"
    networks:
      - api_network
    ports:
      - "8081:8081"

  mongodb_service:
    # fixed version 4.4.6: https://stackoverflow.com/questions/70818543/mongo-db-deployment-not-working-in-kubernetes-because-processor-doesnt-have-avx
    image: mongo:4.4.6
    restart: always
    networks:
      - api_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  docusaurus_service:
    image: "registry.gitlab.com/jamesari/aswi-testing/doc-dist:latest"
    networks:
      - api_network
    ports:
      - "3000:3000"
  
volumes:
  mongo_data:

networks:
  api_network:
