version: '3'

services:
  web_service:
    build: ./web
    networks:
      - api_network
    ports:
      - "8080:8080"

  ai_service:
    build: ./ai
    networks:
      - api_network
    ports:
      - "8081:8081"

  mongodb_service:
    image: mongo:4.4.6
    restart: always
    networks:
      - api_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
volumes:
  mongo_data:

networks:
  api_network:
