- name: Create base dir for app
  become: true
  ansible.builtin.file:
    path: "{{ app_base_dir }}"
    mode: "0775"
    owner: "{{ gc_app_user }}"
    group: "{{ gc_app_group }}"
    state: "directory"

- name: Copy Docker Compose files
  become: true
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: "{{ app_base_dir }}/{{ item }}"
  loop:
  - docker-compose.prod.yml

- name: Deploy Docker Compose stack
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ app_base_dir }}"
    pull: always
    state: present
    files:
      - docker-compose.prod.yml

# - name: Run the app docker image
#   become: true
#   docker_container:
#     name: "{{ gitlab_image_name }}"
#     image: "{{ gitlab_image_url }}"
#     state: started
#     restart_policy: always
#     restart: true
#     pull: true
#     cleanup: true
#     ports:
#       - "80:8080"
#     env:
#       NODE_ENV: "production"
#       PORT: "8080"
